@Warehouse_HostAddress = https://localhost:7272

### 1. GET ALL CATEGORIES
GET {{Warehouse_HostAddress}}/api/category
Accept: application/json

###

### 2. GET SINGLE CATEGORY 
GET {{Warehouse_HostAddress}}/api/category/1
Accept: application/json